### ISSUE TITLE
fix: null check operator used on a null value

### ISSUE THREAD

**Issue by marcossevilla** [felangel/mason#140]
**Description**

When generating a project from a config.json file, the mason generator fails with this output:
```
Null check operator used on a null value
#0      TemplateFile.runSubstitution (package:mason/src/generator.dart:329:60)
#1      Generator.generate.<anonymous closure> (package:mason/src/generator.dart:157:34)
#2      Generator.generate.<anonymous closure> (package:mason/src/generator.dart:150:47)
#3      Future.forEach.<anonymous closure> (dart:async/future.dart:495:26)
#4      Future.doWhile.<anonymous closure> (dart:async/future.dart:535:26)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#6      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1659:26)
<asynchronous suspension>
#7      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart)
<asynchronous suspension>
```

**Expected Behavior**

Should generate correctly with config.json file specified.

**Screenshots**

**Additional Context**

**Comment by marcossevilla** [comment]
Related [felangel/mason#140](https://github.com/felangel/mason/issues/140).
