### ISSUE TITLE
fix: Crashes when no argument to 'new' is provided

### ISSUE THREAD

**Issue by Ascenio** [felangel/mason#37]
**Description**
When the user tries to create a new brick without providing the name, the tool crashes.

**Steps To Reproduce**
1. Open a mason project
2. Type exactly `mason new`
3. Profit

**Expected Behavior**
Should prompt the help menu the same way as `mason make`

**Logs**
```dart
$ mason new
Unhandled exception:
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:99:22)
#1      NewCommand.run (package:mason/src/commands/new.dart:37:34)
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      MasonCommandRunner.runCommand (package:mason/src/command_runner.dart:64:18)
#4      MasonCommandRunner.run (package:mason/src/command_runner.dart:39:20)
#5      main (file:///home/ascenio/.pub-cache/hosted/pub.dartlang.org/mason-0.0.1-dev.27/bin/mason.dart:5:50)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```

**Comment by felangel** [comment]
This has been addressed by #46 and published in v0.0.1-dev.30 👍
